### PR TITLE
Update debug.hpp

### PR DESCRIPTION
**Pull request by CSSDStudioCXY**

### CODE REVIEW

**Comment by flyingpig233-cpu** [comment]
Sorry, I think it is unnecessary, it breaks my idea. Howerver, thank you for your pull request.

**Comment by samzhangjy** [comment]
Great code. I think @flyingpig233-cpu can approve it. This kind of code will surely help to maintain this project in the future.

**Comment by flyingpig233-cpu** [comment]
> Great code. I think @flyingpig233-cpu can approve it. This kind of code will surely help to maintain this project in the future.

I think, it is more suit for you @samzhangjy

**Comment by flyingpig233-cpu** [comment]
@CSSDStudioCXY 你可以去samzhangjy的项目里发挥你的余热

**Pull request closed without merging**
